# Generated by Django 3.2.9 on 2021-12-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20201205_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gingerhouse',
            options={'ordering': ['-category__name']},
        ),
        migrations.RemoveField(
            model_name='gingerhouse',
            name='image',
        ),
    ]
